# Generated by Django 4.2.4 on 2023-09-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='special',
            new_name='Diseases',
        ),
    ]
